// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppProto.proto

package ./;

/**
 * Protobuf type {@code uc.mei.is.Teacher}
 */
public final class Teacher extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:uc.mei.is.Teacher)
    TeacherOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Teacher.newBuilder() to construct.
  private Teacher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Teacher() {
    students_ = java.util.Collections.emptyList();
    name_ = "";
    birthdate_ = "";
    address_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Teacher();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Teacher(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              students_ = new java.util.ArrayList<./.Student>();
              mutable_bitField0_ |= 0x00000001;
            }
            students_.add(
                input.readMessage(./.Student.PARSER, extensionRegistry));
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            name_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            birthdate_ = bs;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000004;
            telephone_ = input.readInt32();
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            address_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        students_ = java.util.Collections.unmodifiableList(students_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ./.AppProto.internal_static_uc_mei_is_Teacher_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ./.AppProto.internal_static_uc_mei_is_Teacher_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ./.Teacher.class, ./.Teacher.Builder.class);
  }

  private int bitField0_;
  public static final int STUDENTS_FIELD_NUMBER = 1;
  private java.util.List<./.Student> students_;
  /**
   * <code>repeated .uc.mei.is.Student students = 1;</code>
   */
  @java.lang.Override
  public java.util.List<./.Student> getStudentsList() {
    return students_;
  }
  /**
   * <code>repeated .uc.mei.is.Student students = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ./.StudentOrBuilder> 
      getStudentsOrBuilderList() {
    return students_;
  }
  /**
   * <code>repeated .uc.mei.is.Student students = 1;</code>
   */
  @java.lang.Override
  public int getStudentsCount() {
    return students_.size();
  }
  /**
   * <code>repeated .uc.mei.is.Student students = 1;</code>
   */
  @java.lang.Override
  public ./.Student getStudents(int index) {
    return students_.get(index);
  }
  /**
   * <code>repeated .uc.mei.is.Student students = 1;</code>
   */
  @java.lang.Override
  public ./.StudentOrBuilder getStudentsOrBuilder(
      int index) {
    return students_.get(index);
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIRTHDATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object birthdate_;
  /**
   * <code>optional string birthdate = 3;</code>
   * @return Whether the birthdate field is set.
   */
  @java.lang.Override
  public boolean hasBirthdate() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string birthdate = 3;</code>
   * @return The birthdate.
   */
  @java.lang.Override
  public java.lang.String getBirthdate() {
    java.lang.Object ref = birthdate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        birthdate_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string birthdate = 3;</code>
   * @return The bytes for birthdate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBirthdateBytes() {
    java.lang.Object ref = birthdate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      birthdate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TELEPHONE_FIELD_NUMBER = 4;
  private int telephone_;
  /**
   * <code>optional int32 telephone = 4;</code>
   * @return Whether the telephone field is set.
   */
  @java.lang.Override
  public boolean hasTelephone() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 telephone = 4;</code>
   * @return The telephone.
   */
  @java.lang.Override
  public int getTelephone() {
    return telephone_;
  }

  public static final int ADDRESS_FIELD_NUMBER = 5;
  private volatile java.lang.Object address_;
  /**
   * <code>optional string address = 5;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string address = 5;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        address_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string address = 5;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < students_.size(); i++) {
      output.writeMessage(1, students_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, birthdate_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(4, telephone_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < students_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, students_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, birthdate_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, telephone_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ./.Teacher)) {
      return super.equals(obj);
    }
    ./.Teacher other = (./.Teacher) obj;

    if (!getStudentsList()
        .equals(other.getStudentsList())) return false;
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasBirthdate() != other.hasBirthdate()) return false;
    if (hasBirthdate()) {
      if (!getBirthdate()
          .equals(other.getBirthdate())) return false;
    }
    if (hasTelephone() != other.hasTelephone()) return false;
    if (hasTelephone()) {
      if (getTelephone()
          != other.getTelephone()) return false;
    }
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStudentsCount() > 0) {
      hash = (37 * hash) + STUDENTS_FIELD_NUMBER;
      hash = (53 * hash) + getStudentsList().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasBirthdate()) {
      hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthdate().hashCode();
    }
    if (hasTelephone()) {
      hash = (37 * hash) + TELEPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getTelephone();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ./.Teacher parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ./.Teacher parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ./.Teacher parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ./.Teacher parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ./.Teacher parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ./.Teacher parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ./.Teacher parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ./.Teacher parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ./.Teacher parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ./.Teacher parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ./.Teacher parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ./.Teacher parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(./.Teacher prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code uc.mei.is.Teacher}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:uc.mei.is.Teacher)
      ./.TeacherOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ./.AppProto.internal_static_uc_mei_is_Teacher_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ./.AppProto.internal_static_uc_mei_is_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ./.Teacher.class, ./.Teacher.Builder.class);
    }

    // Construct using ./.Teacher.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStudentsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (studentsBuilder_ == null) {
        students_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        studentsBuilder_.clear();
      }
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      birthdate_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      telephone_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      address_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ./.AppProto.internal_static_uc_mei_is_Teacher_descriptor;
    }

    @java.lang.Override
    public ./.Teacher getDefaultInstanceForType() {
      return ./.Teacher.getDefaultInstance();
    }

    @java.lang.Override
    public ./.Teacher build() {
      ./.Teacher result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ./.Teacher buildPartial() {
      ./.Teacher result = new ./.Teacher(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (studentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          students_ = java.util.Collections.unmodifiableList(students_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.students_ = students_;
      } else {
        result.students_ = studentsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.birthdate_ = birthdate_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.telephone_ = telephone_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.address_ = address_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ./.Teacher) {
        return mergeFrom((./.Teacher)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(./.Teacher other) {
      if (other == ./.Teacher.getDefaultInstance()) return this;
      if (studentsBuilder_ == null) {
        if (!other.students_.isEmpty()) {
          if (students_.isEmpty()) {
            students_ = other.students_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStudentsIsMutable();
            students_.addAll(other.students_);
          }
          onChanged();
        }
      } else {
        if (!other.students_.isEmpty()) {
          if (studentsBuilder_.isEmpty()) {
            studentsBuilder_.dispose();
            studentsBuilder_ = null;
            students_ = other.students_;
            bitField0_ = (bitField0_ & ~0x00000001);
            studentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentsFieldBuilder() : null;
          } else {
            studentsBuilder_.addAllMessages(other.students_);
          }
        }
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasBirthdate()) {
        bitField0_ |= 0x00000004;
        birthdate_ = other.birthdate_;
        onChanged();
      }
      if (other.hasTelephone()) {
        setTelephone(other.getTelephone());
      }
      if (other.hasAddress()) {
        bitField0_ |= 0x00000010;
        address_ = other.address_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ./.Teacher parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (./.Teacher) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<./.Student> students_ =
      java.util.Collections.emptyList();
    private void ensureStudentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        students_ = new java.util.ArrayList<./.Student>(students_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ./.Student, ./.Student.Builder, ./.StudentOrBuilder> studentsBuilder_;

    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public java.util.List<./.Student> getStudentsList() {
      if (studentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(students_);
      } else {
        return studentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public int getStudentsCount() {
      if (studentsBuilder_ == null) {
        return students_.size();
      } else {
        return studentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public ./.Student getStudents(int index) {
      if (studentsBuilder_ == null) {
        return students_.get(index);
      } else {
        return studentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public Builder setStudents(
        int index, ./.Student value) {
      if (studentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentsIsMutable();
        students_.set(index, value);
        onChanged();
      } else {
        studentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public Builder setStudents(
        int index, ./.Student.Builder builderForValue) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public Builder addStudents(./.Student value) {
      if (studentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentsIsMutable();
        students_.add(value);
        onChanged();
      } else {
        studentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public Builder addStudents(
        int index, ./.Student value) {
      if (studentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentsIsMutable();
        students_.add(index, value);
        onChanged();
      } else {
        studentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public Builder addStudents(
        ./.Student.Builder builderForValue) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.add(builderForValue.build());
        onChanged();
      } else {
        studentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public Builder addStudents(
        int index, ./.Student.Builder builderForValue) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public Builder addAllStudents(
        java.lang.Iterable<? extends ./.Student> values) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, students_);
        onChanged();
      } else {
        studentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public Builder clearStudents() {
      if (studentsBuilder_ == null) {
        students_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        studentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public Builder removeStudents(int index) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.remove(index);
        onChanged();
      } else {
        studentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public ./.Student.Builder getStudentsBuilder(
        int index) {
      return getStudentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public ./.StudentOrBuilder getStudentsOrBuilder(
        int index) {
      if (studentsBuilder_ == null) {
        return students_.get(index);  } else {
        return studentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public java.util.List<? extends ./.StudentOrBuilder> 
         getStudentsOrBuilderList() {
      if (studentsBuilder_ != null) {
        return studentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(students_);
      }
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public ./.Student.Builder addStudentsBuilder() {
      return getStudentsFieldBuilder().addBuilder(
          ./.Student.getDefaultInstance());
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public ./.Student.Builder addStudentsBuilder(
        int index) {
      return getStudentsFieldBuilder().addBuilder(
          index, ./.Student.getDefaultInstance());
    }
    /**
     * <code>repeated .uc.mei.is.Student students = 1;</code>
     */
    public java.util.List<./.Student.Builder> 
         getStudentsBuilderList() {
      return getStudentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ./.Student, ./.Student.Builder, ./.StudentOrBuilder> 
        getStudentsFieldBuilder() {
      if (studentsBuilder_ == null) {
        studentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ./.Student, ./.Student.Builder, ./.StudentOrBuilder>(
                students_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        students_ = null;
      }
      return studentsBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object birthdate_ = "";
    /**
     * <code>optional string birthdate = 3;</code>
     * @return Whether the birthdate field is set.
     */
    public boolean hasBirthdate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string birthdate = 3;</code>
     * @return The birthdate.
     */
    public java.lang.String getBirthdate() {
      java.lang.Object ref = birthdate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          birthdate_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string birthdate = 3;</code>
     * @return The bytes for birthdate.
     */
    public com.google.protobuf.ByteString
        getBirthdateBytes() {
      java.lang.Object ref = birthdate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string birthdate = 3;</code>
     * @param value The birthdate to set.
     * @return This builder for chaining.
     */
    public Builder setBirthdate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      birthdate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string birthdate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBirthdate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      birthdate_ = getDefaultInstance().getBirthdate();
      onChanged();
      return this;
    }
    /**
     * <code>optional string birthdate = 3;</code>
     * @param value The bytes for birthdate to set.
     * @return This builder for chaining.
     */
    public Builder setBirthdateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      birthdate_ = value;
      onChanged();
      return this;
    }

    private int telephone_ ;
    /**
     * <code>optional int32 telephone = 4;</code>
     * @return Whether the telephone field is set.
     */
    @java.lang.Override
    public boolean hasTelephone() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 telephone = 4;</code>
     * @return The telephone.
     */
    @java.lang.Override
    public int getTelephone() {
      return telephone_;
    }
    /**
     * <code>optional int32 telephone = 4;</code>
     * @param value The telephone to set.
     * @return This builder for chaining.
     */
    public Builder setTelephone(int value) {
      bitField0_ |= 0x00000008;
      telephone_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 telephone = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTelephone() {
      bitField0_ = (bitField0_ & ~0x00000008);
      telephone_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>optional string address = 5;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string address = 5;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000010);
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 5;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      address_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:uc.mei.is.Teacher)
  }

  // @@protoc_insertion_point(class_scope:uc.mei.is.Teacher)
  private static final ./.Teacher DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ./.Teacher();
  }

  public static ./.Teacher getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Teacher>
      PARSER = new com.google.protobuf.AbstractParser<Teacher>() {
    @java.lang.Override
    public Teacher parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Teacher(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Teacher> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Teacher> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ./.Teacher getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

